### PR TITLE
Overflow with flowkit 1

### PR DESCRIPTION
**Pull request by benbackend**

### CODE REVIEW

**Comment by Bamthelearner** [comment]
one of the tests is failing : 

In this test, it is supposed to mint an NFT and fail at NFT init function. 
Seems that the error message didn't go that far to print out the error at NFT init function. 
But, instead, returned at the line that "create NFT"

```
💩 Error executing transaction: devMintExampleNFT error:execution error code 1101: [Error Code: 1101] error caused by: 1 error occurred:
	* transaction execute failed: [Error Code: 1101] cadence runtime error: Execution failed:
  --> 57b4f4fa48719c766e305a6df247c445a18568d5fdf73bb3e37f7fe467b209ff:56:2
   |
56 | 		FindForge.mint(lease: lease, forgeType: forgeType, data: mintData, receiver: nftReceiver)
   | 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   --> 179b6b1cb6755e31.FindForge:265:2
    |
265 | 		FindForge.adminMint(lease: leaseName, forgeType: forgeType , data: data, receiver: receiver)
    | 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   --> 179b6b1cb6755e31.FindForge:289:13
    |
289 | 		let nft <- forge.mint(platform: minterPlatform, data: data, verifier: verifier)
    | 		           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   --> 179b6b1cb6755e31.ExampleNFT:311:13
    |
311 | 			return <- ExampleNFT.mintNFT(name: info.name,
312 |                                         description: info.description,
313 |                                         thumbnail: info.thumbnail,
314 |                                         soulBound: info.soulBound,
315 |                                         traits: info.traits,
316 |                                         royalties: MetadataViews.Royalties(royalties))
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   --> 179b6b1cb6755e31.ExampleNFT:287:29
    |
287 |         var newNFT <- create NFT(
288 |             id: ExampleNFT.totalSupply,
289 |             name: name,
290 |             description: description,
291 |             thumbnail: thumbnail,
292 |             soulBound: soulBound,
293 |             traits: traits,
294 |             royalties: royalties
295 |         )
    |
```

**Comment by Bamthelearner** [comment]
@bjartek FYI

**Comment by sideninja** [comment]
This is really weird. What is used to send a transaction? flowkit? I don't understand why would that be cut, will look into it tho, thanks for reporting.

**Comment by bjartek** [comment]
I traced this all the way back to EmulatorGateway GetTransactionResult and there the message is truncated from the Emulator. So maybe this is an emulator bug and not a cli bug?

**Review by bjartek — APPROVED** [review]

**Pull request merged**
