### PR TITLE
add multiple trxns for sale

### PR DESCRIPTION
**Pull request by Bamthelearner**

### CODE REVIEW

**Comment by bjartek** [comment]
Dapper does not support buying multiple items at the moment they have told me.

**Comment by bjartek** [comment]
Given that FindLeaseMarket is only used with dapper wallet and that dapper wallet does not support this I am not sure if this is needed?

**Review by bjartek — CHANGES_REQUESTED** [review]
See comments in pr.

**Comment by Bamthelearner** [comment]
changed the bulk trxn to support only non-dapper wallets.

**Review by bjartek — APPROVED** [review]

**Pull request merged**
